name: NekoUtility
version: '1.3.2'
main: nekoutility.Main
authors: [LukeTheNeko]

commands:
  echest:
    default: false
    aliases:
      - ec
      - enderchest

  fly:
    default: false
    aliases:
      - voar

  tp:
    default: false
    aliases:
    - teleport

  rename:
    default: false

  relore:
    default: false

  gm:
    default: false

  hat:
    default: false

  heal:
    default: false

  luz:
    default: false

  enchant:
    aliases:
      - encantar

  vanish:
    default: false
    aliases:
      - v

  invsee:
    default: false

  clear:
    default: false

  speed:
    default: false

permissions:
  nekoutility.admin:
    default: false

  nekoutility.ec:
    default: false

  NekoUtility.adm.ec:
    default: false

  nekoutility.fly:
    default: false

  nekoutility.heal:
    default: false

  nekoutility.luz:
    default: false

  nekoutility.rename:
    default: false

  nekoutility.relore:
    default: false

  nekoutility.enchant:
    default: false

  nekoutility.tp:
    default: false

  nekoutility.invsee:
    default: false

  nekoutility.clear:
    default: false

  inventory-cleared-others:
    default: true

  nekoutility.speed:
    default: false